"""Prepare official MobRecon static geometry without MANO_RIGHT.pkl.

Only the four exact data constructors used by the public transform file are
allowed. Mesh spiral ordering is generated by the official OpenMesh algorithm.
This is an experimental preparation step, not a model-license clearance.
"""

import pickle
import sys
from pathlib import Path

import numpy as np
import scipy.sparse as sparse

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "source"))


class DataUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        allowed = {
            ("numpy", "dtype"): np.dtype,
            ("numpy", "ndarray"): np.ndarray,
            ("numpy.core.multiarray", "_reconstruct"): np.core.multiarray._reconstruct,
            ("scipy.sparse.csc", "csc_matrix"): sparse.csc_matrix,
        }
        if (module, name) not in allowed:
            raise pickle.UnpicklingError(f"Unexpected constructor {module}.{name}")
        return allowed[module, name]


def main():
    from utils.utils import preprocess_spiral

    with (ROOT / "source/template/transform.pkl").open("rb") as stream:
        mesh = DataUnpickler(stream, encoding="latin1").load()
    arrays = {}
    for index in range(4):
        arrays[f"spiral_{index}"] = preprocess_spiral(
            mesh["face"][index], 9, mesh["vertices"][index], 1
        ).numpy()
        matrix = mesh["up_transform"][index].tocoo()
        arrays[f"up_row_{index}"] = matrix.row.astype(np.int64)
        arrays[f"up_col_{index}"] = matrix.col.astype(np.int64)
        arrays[f"up_val_{index}"] = matrix.data.astype(np.float32)
    arrays["joint_regressor"] = np.load(
        ROOT / "source/template/j_reg.npy", allow_pickle=False
    )
    arrays["faces"] = mesh["face"][0]
    np.savez(ROOT / "geometry.npz", **arrays)
    print({name: value.shape for name, value in arrays.items()})


if __name__ == "__main__":
    main()
